site_name: Python Cheatsheet
site_description: Personal Python notes & code snippets
site_author: Alessandro

theme:
  name: material
  language: en
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy

  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Dark mode

    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Light mode

markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.tabbed
  - toc:
      permalink: true

plugins:
  - search
nav:
  - Basics Concepts:
      - basics/execute_code.md
      - basics/printing.md
      - basics/strings.md
      - basics/input.md
      - basics/variables.md
      - basics/data_types.md
      - basics/math_ops.md
      - basics/time.md
      - basics/decorators.md
  - Flow control:
      - flow_control/logical_operators.md
      - flow_control/if_statement.md
      - flow_control/for_statement.md
      - flow_control/while_statement.md
  - Error handling:
      - error_handling/index.md
  - Collections:
      - collections/index.md
      - collections/lists.md
      - collections/tuples.md
      - collections/dictionaries.md
  - Functions:
      - functions/index.md
  - Modules:
      - modules/index.md
  - Namespaces:
      - namespaces_scopes/index.md
  - FileSystem:
      - file_system/index.md
  - OOP:
      - oop/index.md
      - oop/packages.md
  - File formats:
      - file_formats/csv_format.md
      - file_formats/json_files.md
  - Persistence:
      - persistence/index.md
      - persistence/tinydb.md
      - persistence/sqlite.md
  - Data Analysis:
      - data_analysis/pandas.md
  - Networking:
      - networking/api.md
      - networking/authentication_methods.md
      - networking/web_sever_with_flask.md
  - GUI:
      - gui/gui_with_tkinter.md
  - Applications:
      - applications/emails.md
      - applications/telegram.md
  - Cloud:
      - cloud/run_in_the_cloud.md
  - Itertools:
      - itertools/index.md
  - Async:
      - async/index.md
  - Typing:
      - typing/index.md
  - Gotchas:
      - gotchas/index.md
  - MKDocs Tutorial:
      index.md
